### ISSUE TITLE
TypeError when running main.py

### ISSUE THREAD

**Issue by bjornasm** [inconvergent/sand-creatures#2]
When I run main.py without colours (see other issue) I get the following error:

`/lib/python3.5/site-packages/cairocffi-0.7.2-py3.5.egg/cairocffi/surfaces.py:651: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  ffi.cast('char*', address), format, width, height, stride)

Traceback (most recent call last):

  File "main.py", line 80, in <module>
    main()

  File "main.py", line 73, in main
    make_creatures(sand)

  File "main.py", line 59, in make_creatures
    sand.paint_strokes(l1, l2, GRAINS)

  File "src/sand.pyx", line 392, in sand.Sand.paint_strokes (./src/sand.c:7678)

  File "stringsource", line 644, in View.MemoryView.memoryview_cwrapper (./src/sand.c:20025)

  File "stringsource", line 345, in View.MemoryView.memoryview.__cinit__ (./src/sand.c:16155)

TypeError: a bytes-like object is required, not 'int'`

**Comment by inconvergent** [comment]
i changed things around a while back. i'm not going to start fixing this right now. you need to replace GRAINS with ones(len(l1), 'int)*GRAINS. ones is imported from numpy, if it's not imported already.
